# dang nhap
POST http://localhost/vegetable-website/server/login.php
Content-Type: application/x-www-form-urlencoded

email=admin@admin.com&password=123456

###

# dang xuat
POST http://localhost/vegetable-website/server/logout.php

###



